server:
  port: 8090
spring:
  profiles:
    active: dev
---
server:
  port: 8080
spring:
  profiles: dev
---
server:
  port: 8070
spring:
  profiles: prod  #指定属于那种环境
#person:
#  lastName: hello
#  age: 19
#  isBoss: false
#  birth: 1998/4/2
#  maps: {k: v,k2: v2}
#  lists:
#    - dog
#    - cat
#    - pig
#  dog:
#    name: 小
#    age: 2